directories:
  output: dist_electron
  buildResources: build
appId: com.grupomanhattan.tpv
productName: TPV Grupo Manhattan
files:
  - filter:
      - electron/**/*
      - dist/**/*
      - package.json
extraResources:
  - from: ../backend
    to: backend
    filter:
      - '**/*'
  - from: ../backend/node_modules
    to: backend/node_modules
    filter:
      - '**/*'
  - from: build/README_Cliente.txt
    to: README_Cliente.txt
asarUnpack:
  - backend/**/*
asar: true
win:
  target: nsis
  icon: electron/assets/manhattan.ico
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 37.7.0
